### ISSUE TITLE
no such table: transaction

### ISSUE THREAD

**Issue by carloshanson** [bprinty/Flask-Continuum#11]
After playing with flask-migrate and adding Flask-Continuum, I decided to start with Flask-Continuum, then add flask-migrate, but I can't get Flask-Continuum to work from the documentation.

```python
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_continuum import Continuum

app = Flask(__name__)
db = SQLAlchemy(app)
continuum = Continuum(app, db)

from flask_continuum import VersioningMixin

# defining database schema
class Article(db.Model, VersioningMixin):
    __tablename__ = 'article'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.Unicode(255))
    content = db.Column(db.UnicodeText)
```

All I did was combine the two minimal app examples, then ran the following:

```python
$ flask shell
>>> from app import db, Article
>>> article = Article(name='Some article', content='Some content') 
>>> db.session.add(article)
>>> db.session.commit()
[...]
sqlite3.OperationalError: no such table: transaction
[...]
```

What am I missing?

Thanks.

**Comment by bprinty** [comment]
I was able to reproduce this issue when database tables hadn't been created before trying to commit date.  The `no such table: transaction` is a bit of a red herring - if you weren't using `Flask-Continuum`, I think you'd see an  error like "no such table: articles". Here is what you can try to resolve the issue:

```python
$ flask shell
>>> from app import db, Article
>>> db.create_all()
>>> article = Article(name='Some article', content='Some content') 
>>> db.session.add(article)
>>> db.session.commit()
``` 

In general, you'll want to make sure `db.create_all()` has been run before you start using a database in the application.

**Comment by bprinty** [comment]
Also, I've added this and the previous ticket to a [Troubleshooting](https://flask-continuum.readthedocs.io/en/latest/usage.html#troubleshooting) section of the documentation. I'll keep updating that section as new problems come up. Thanks for the input!

**Comment by josipbudzaki** [comment]
I've had a similar problem: transaction and version tables were not created. After fiddling around I found out that in my configuration, I have to run `db.create_all()` twice.
1. `db.create_all(app=create_app())` with [context](https://flask-sqlalchemy.palletsprojects.com/en/2.x/contexts/)
2. `db.create_all()`

For reference, here's the whole code:
```python

from flask import Flask
from flask_continuum import Continuum, VersioningMixin
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
continuum = Continuum(db=db)


class Article(db.Model, VersioningMixin):
    __tablename__ = 'article'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.Unicode(255))
    content = db.Column(db.UnicodeText)

def make_article():
    article = Article(name='Some article', content='Some content')
    db.session.add(article)
    db.session.commit()


def create_app():
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////database.db'
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
    db.init_app(app)
    app.app_context().push()
    continuum.init_app(app)
    
    return app


if __name__ == '__main__':
    db.create_all(app=create_app())
    db.create_all()
```
